Ignored qualifier warnings in overlay due to issues in lidar_utils:
#28 120.7 --- stderr: lidar_utils
#28 120.7 /opt/overlay_ws/src/AutowareAuto/src/common/lidar_utils/src/point_cloud_utils.cpp: In function ‘autoware::common::types::bool8_t autoware::common::lidar_utils::add_point_to_cloud_raw(sensor_msgs::msg::PointCloud2&, const autoware::common::types::PointXYZIF&, uint32_t)’:
#28 120.7 /opt/overlay_ws/src/AutowareAuto/src/common/lidar_utils/src/point_cloud_utils.cpp:174:87: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
#28 120.7   174 |   const uint8_t * const casted_point_ptr = reinterpret_cast<const uint8_t * const>(&pt);
#28 120.7       |                                                                                       ^
#28 120.7 cc1plus: all warnings being treated as errors
#28 120.7 make[2]: *** [CMakeFiles/lidar_utils.dir/build.make:63: CMakeFiles/lidar_utils.dir/src/point_cloud_utils.cpp.o] Error 1
#28 120.7 make[1]: *** [CMakeFiles/Makefile2:129: CMakeFiles/lidar_utils.dir/all] Error 2
#28 120.7 make: *** [Makefile:141: all] Error 2
#28 120.7 ---